import React from 'react'
import Pixel from './Pixel'

const App = () => (
  <div>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/><Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
  </div>
)

  

export default App
